
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://thealphadollar.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: ""

# Google tracking id

google-tracking-id: "UA-121294295-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "thealphadollar"
title: "{ Cogito, Ergo Sum }"
tagline: "A collection of Shivam's writeups on technology, programming, philosophy, and psychology."
description: "An attempt at encapsulating my life - experiences, thoughts and ideas at one place to share with the world and grow. I frequently publish blogs on technology, programming, developer-operations, philosophy, psychology, and create new interesting projects on Github."
keywords: "thealphadollar, thealpha$, personal, shivam kumar jha, shivam, thealpha, shivam jha, mercari, iitkgp student"
favicon: /img/favicon.ico
logo: /img/author_logo.png

#######
# SEO #
#######
social:
  name: Shivam Kumar Jha
  links:
    - https://facebook.com/thealphadollar
    - https://twitter.com/thealphadollar_
    - https://github.com/thealphadollar
    - https://www.medium.com/@thealphadollar
    - https://www.instagram.com/thealphadollar
    - https://www.linkedin.com/in/thealphadollar

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 7
start-delay: 100
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "<strong>Final</strong> Year undergraduate at IIT Kharagpur..."
  - text: "<strong>Ask forgiveness</strong> not permission, or not even that..."
  - text: "Ice melts quicker when you read..."
  - text: "I would love to have <strong>a coffee, with you...</strong>"
  - text: "If efforts could be gauged, world would have been <strong>...</strong>"
  - text: "I'm influenced by <strong>Sapiens</strong>, <strong>The Courage To Be Disliked</strong>, <strong>The Difficulty of Being Good</strong>, and more..."

# me-img: "/img/me.png"

# Using facebook isn't possible anymore since the change in graph API

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/thealphadollar.png?size=100"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 60

paginate: 7

email-share: False
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "https-thealphathealphadollardollar-github-io"

syntax-highlight: True

###########
# Connect #
###########

email: "coffee@thealphadollar.me"
resume_link: "https://github.com/thealphadollar/my_resume/blob/master/resume_thealphadollar.pdf"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Your typical geek; Shivam can be found toiling hard through books (away from library) to find what she means by her actions
 :wink: Hard at work, and harder at drunk dancing, he loves to find ways to increase his productivity so he can
 invest time elsewhere. When he does get some time, and is in the mood, he writes few lines of code and some lines of rhymes :facepunch:"
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/thealphadollar"
  - title: "twitter"
    url: "https://twitter.com/thealphadollar_"
  - title: "github"
    url: "https://github.com/thealphadollar"
  - title: "medium"
    url: "https://www.medium.com/@thealphadollar"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/thealphadollar"
  - title: "instagram"
    url: "https://www.instagram.com/thealphadollar"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################
#
#keybase-username: <username>
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Tags: 'tags'
  Connect: 'connect'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", ".idea", "2015-06-19-writing-posts.md"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-seo-tag