#!/usr/bin/env ruby

require 'date'
require 'fileutils'

POSTS_DIR = '_posts/'
IMG_DIR = 'img/'

post = ARGV[0]

File.open(POSTS_DIR + Date.today.strftime("%Y-%m-%d-") + post + '.md', 'w') {|f| f.write(
  "---\ntitle: Title\ndescription: Description\nimage: FeaturedImage\ncategory: Category\ntags: [ 'tag1', 'tag2' ]\nlayout: post\ntype: BlogPosting\nsection-type: post\nauthor: thealphadollar\n---")
}

puts('[+] Created ' + post + ' post')

# creates directory for storing images
FileUtils.mkdir_p IMG_DIR + "posts/" + post